<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>8528a3c7-b66b-4497-81bb-c95cf7a01878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='QuickLinks']/a[4]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1a9925e1-6a99-485a-b2e1-cd2f97f5094b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/sm_cats.gif</value>
      <webElementGuid>fe69ee8b-682a-49c1-b535-740be36ec575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QuickLinks&quot;)/a[4]/img[1]</value>
      <webElementGuid>78d41f6d-6e06-432f-8e74-c5d116194c61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='QuickLinks']/a[4]/img</value>
      <webElementGuid>55cd41a4-e1f8-4ec7-a526-4302d72e5786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/img</value>
      <webElementGuid>05d34f92-c96a-4e41-b8ba-32f42978de88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/sm_cats.gif']</value>
      <webElementGuid>530aec97-d70b-4e42-ad76-749f8950710d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
